// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TimelapseMP4Creator.Services.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Hour1400File
    {
        /// <summary>
        /// Initializes a new instance of the Hour1400File class.
        /// </summary>
        public Hour1400File()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Hour1400File class.
        /// </summary>
        public Hour1400File(string fileName = default(string), System.DateTime? dateTaken = default(System.DateTime?))
        {
            FileName = fileName;
            DateTaken = dateTaken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateTaken")]
        public System.DateTime? DateTaken { get; set; }

    }
}
